import { Inter } from "next/font/google";
import "./globals.css";
import Navbar1 from "@/components/Navbar1";
import Footer from "@/components/Footer";
import SmoothScroller from "@/components/SmoothScroll";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SmoothScroller/>
        <Navbar1/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
